name: auth
services:
  keycloak:
    image: 'keycloak/keycloak:23.0'
    command: start-dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
  postgres:
    image: 'postgres:16-alpine'
    #command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=keycloak
